include:
  # dyad
  - board: seeeduino_xiao_ble
    shield: dyad_central_dongle dongle_display
    artifact-name: dyad_central_dongle
  - board: seeeduino_xiao_ble
    shield: dyad_central_left
    artifact-name: dyad_central_left
  - board: seeeduino_xiao_ble
    shield: dyad_peripheral_left
    artifact-name: dyad_peripheral_left
  - board: seeeduino_xiao_ble
    shield: dyad_peripheral_right
    artifact-name: dyad_peripheral_right
  - board: seeeduino_xiao_ble
    shield: settings_reset
  - board: seeeduino_xiao_ble
    shield: dyad_central_dongle dongle_display
    cmake-args: -DCONFIG_ZMK_USB_LOGGING=y
    artifact-name: dyad_central_dongle_with_logging
